app_home:
    path: /
    controller: App\Controller\RaceController::index
    
app_change_password:
    path:       /change_password
    controller: App\Controller\SecurityController::change_password
    